name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'   # каждый день в полночь
  workflow_dispatch:       # можно запускать вручную

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch and update TryHackMe badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "olgakesha59"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
